instanceID: "19192739"

http:
  listener:
    host: "0.0.0.0"
    port: "8081"
  requester:
    customer:
      sapi:
        host: " customer-sapi-app-v1.us-e2.cloudhub.io"
        port: ""
        pathCustomerState: "api/customerState?featureName=cf"
    
sfdc:
  username: "kumar@vsoft.sandbox"
  password: "Srimanthoju@4793"
  securityToken : "9VTMX6YcdqxiO4Y5RBruad2q"