#%RAML 1.0 Trait
headers:
  x-cms-transactionId: 
    type: string
    required: true
    minLength: 36
    maxLength: 36
    example: "hdsfhjdh-jxbv859-sjdf7643-3746bbd236"
  clientId:
    type: string
    required: true
    example: "hdsfhjdhjxbv859sjdf76433746bbd236"
  clientSecret:
    type: string
    required: true
    example: "hdsfhjdhjxbv859sjdf76433746bbd236"