#%RAML 1.0 DataType
type: object
properties:
  registrationResponse:
    type: object
    required: true
    properties:
      eventInstanceId:
        type: string
        required: true
        example: "fdgdgdgdfgdgdfgdfgdfgd"
      status:
        type: string
        required: true
        enum:
          - Success
          - Failure
        example: "Success"